project:
  type: book
  output-dir: docs
  
book:
  title: "CASA0023 Learning Diary"
  author: "Zack Zheng"
  chapters:
    - index.qmd
    - week1.qmd
    - week2.qmd

format:
  html:
    theme: cosmo

